version: '3.3'
services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - hosts
    environment:
      - DB_HOST=hosts
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DATABASE
      - DB_PORT=$POSTGRES_LOCAL_PORT
    stdin_open: true
    tty: true

networks:
  hosts: